services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FriendsOfTYPO3\Kickstarter\:
    resource: '../Classes/*'

  FriendsOfTYPO3\Kickstarter\Configuration\ExtConf:
    public: true

  ##############
  ## COMMANDS ##
  ##############

  FriendsOfTYPO3\Kickstarter\Command\ApplyTypo3CglCommand:
    arguments:
      $questionCollection: '@questions.apply-typo3-cgl'

  FriendsOfTYPO3\Kickstarter\Command\CommandCommand:
    arguments:
      $questionCollection: '@questions.command'

  FriendsOfTYPO3\Kickstarter\Command\ControllerCommand:
    arguments:
      $questionCollection: '@questions.controller'

  FriendsOfTYPO3\Kickstarter\Command\EventCommand:
    arguments:
      $questionCollection: '@questions.event'

  FriendsOfTYPO3\Kickstarter\Command\EventListenerCommand:
    arguments:
      $questionCollection: '@questions.event-listener'

  FriendsOfTYPO3\Kickstarter\Command\ExtensionCommand:
    arguments:
      $questionCollection: '@questions.extension'

  FriendsOfTYPO3\Kickstarter\Command\LocallangCommand:
    arguments:
      $questionCollection: '@questions.locallang'

  FriendsOfTYPO3\Kickstarter\Command\MiddlewareCommand:
    arguments:
      $questionCollection: '@questions.middleware'

  FriendsOfTYPO3\Kickstarter\Command\ModelCommand:
    arguments:
      $questionCollection: '@questions.model'

  FriendsOfTYPO3\Kickstarter\Command\ModuleCommand:
    arguments:
      $questionCollection: '@questions.module'

  FriendsOfTYPO3\Kickstarter\Command\PluginCommand:
    arguments:
      $questionCollection: '@questions.plugin'

  FriendsOfTYPO3\Kickstarter\Command\RepositoryCommand:
    arguments:
      $questionCollection: '@questions.repository'

  FriendsOfTYPO3\Kickstarter\Command\ServicesYamlCommand:
    arguments:
      $questionCollection: '@questions.services-yaml'

  FriendsOfTYPO3\Kickstarter\Command\SitePackageCommand:
    arguments:
      $questionCollection: '@questions.site-package'

  FriendsOfTYPO3\Kickstarter\Command\SiteSetCommand:
    arguments:
      $questionCollection: '@questions.site-set'

  FriendsOfTYPO3\Kickstarter\Command\SiteSettingsDefinitionCommand:
    arguments:
      $questionCollection: '@questions.site-settings-definition'

  FriendsOfTYPO3\Kickstarter\Command\TableCommand:
    arguments:
      $questionCollection: '@questions.table'

  FriendsOfTYPO3\Kickstarter\Command\TestEnvCommand:
    arguments:
      $questionCollection: '@questions.test-env'

  FriendsOfTYPO3\Kickstarter\Command\TypeConverterCommand:
    arguments:
      $questionCollection: '@questions.type-converter'

  FriendsOfTYPO3\Kickstarter\Command\UpgradeWizardCommand:
    arguments:
      $questionCollection: '@questions.upgrade-wizard'

  FriendsOfTYPO3\Kickstarter\Command\ValidatorCommand:
    arguments:
      $questionCollection: '@questions.validator'

  ###############
  ## QUESTIONS ##
  ###############

  factory.question:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionFactory

  questions.apply-typo3-cgl:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.apply-typo3-cgl' }

  questions.command:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.command' }

  questions.controller:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.controller' }

  questions.event:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.event' }

  questions.event-listener:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.event-listener' }

  questions.extension:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.extension' }

  questions.locallang:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.locallang' }

  questions.middleware:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.middleware' }

  questions.model:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.model' }

  questions.module:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.module' }

  questions.plugin:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.plugin' }

  questions.repository:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.repository' }

  questions.services-yaml:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.services-yaml' }

  questions.site-package:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.site-package' }

  questions.site-set:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.site-set' }

  questions.site-settings-definition:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.site-settings-definition' }

  questions.table:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.table' }

  questions.test-env:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.test-env' }

  questions.type-converter:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.type-converter' }

  questions.upgrade-wizard:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.upgrade-wizard' }

  questions.validator:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.validator' }
