name: Backport

on:
  pull_request_target:
    types: [closed, labeled]

jobs:
  backport:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v 7.0.1

      - name: Backport
        uses: korthout/backport-action@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
